---
- name: Install python-psycopg2
  yum:
    name: python-psycopg2
    state: present


- name: Smoketest Postgres database
  postgresql_ping:
    db: flask_db
    login_host: "{{ groups.database_servers[0] }}"
    login_user: flask
    login_password: redhat
    ssl_mode: disable
  delegate_to: "{{ groups.app_servers[0] }}"
  run_once: true
  tags:
    - smoketest

